version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: crm-postgres-dev
    environment:
      POSTGRES_DB: crm_nexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-dev:
    image: redis:7-alpine
    container_name: crm-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
