# CRM Nexus Alerting Rules
groups:
  - name: crm-nexus.rules
    rules:
      # High-level application alerts
      - alert: CRMAPIDown
        expr: up{job="crm-api"} == 0
        for: 1m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "CRM API is down"
          description: "CRM API has been down for more than 1 minute"

      - alert: CRMWebDown
        expr: up{job="crm-web"} == 0
        for: 1m
        labels:
          severity: critical
          service: web
        annotations:
          summary: "CRM Web application is down"
          description: "CRM Web application has been down for more than 1 minute"

      # Database alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL connection usage is above 80%"

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been down for more than 1 minute"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is above 90%"

      # System resource alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 5 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85% for more than 5 minutes"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10%"

      # Application performance alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is above 1 second"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High error rate"
          description: "Error rate is above 5% for more than 5 minutes"

      # Business logic alerts
      - alert: HighFailedLogins
        expr: rate(crm_failed_logins_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High number of failed logins"
          description: "Failed login rate is above 10 per minute"

      - alert: LowQuoteConversionRate
        expr: crm_quote_conversion_rate < 0.15
        for: 30m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Low quote conversion rate"
          description: "Quote conversion rate has dropped below 15%"

      - alert: HighCustomerChurnRate
        expr: crm_customer_churn_rate > 0.05
        for: 1h
        labels:
          severity: warning
          service: business
        annotations:
          summary: "High customer churn rate"
          description: "Customer churn rate is above 5%"

      # Security alerts
      - alert: SuspiciousActivity
        expr: rate(crm_suspicious_activity_total[5m]) > 5
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Suspicious activity detected"
          description: "Suspicious activity rate is above 5 per minute"

      - alert: UnauthorizedAccess
        expr: rate(http_requests_total{status="403"}[5m]) > 20
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High number of unauthorized access attempts"
          description: "403 error rate is above 20 per minute"