export { PrismaClient } from './generated';
export * from './generated';

// Re-export commonly used types
export type {
  User,
  Client,
  Contact,
  Lead,
  Deal,
  Job,
  Activity,
  Task,
  Appointment,
  Room,
  JobDayLog,
  InstallerCompany,
  DesignVersion,
  Moodboard,
  ParsedSpecItem,
  Snag,
  Document,
  HandoverPack,
  Guide,
  UserRole,
  LeadStatus,
  JobStatus,
  ActivityType,
  TaskStatus,
  Priority,
  RoomType,
  ClientType,
  Direction,
  AppointmentStatus,
  DesignStatus,
  SnagStatus,
  DocumentCategory,
  FormCategory,
  SyncStatus,
} from './generated';
